---
version: 1
service:
  name: '{{ env "bamboo_deploy_environment" }}-{{ env "bamboo_shortPlanName" }}'
  shortname: ""
  owner: lab
deployment:
  strategy: blueGreen
health:
  delayseconds: 0
  path: "/"
  port: 8989
args:
  - "-pg"
  - "/data/graphdata/graphdata_b_hh_lndn_dnmrk.osm-gh"
  - "-dp"
  - "s3://lab-graphhopper-graphdata/graphdata_b_hh_lndn_dnmrk.gz"
ports:
  - 8989
ingress:
  hosts:
    - host: 'graphhopper.api.{{ env "bamboo_dev_host" }}'
      public: false
autoscaling:
  min: 2
  max: 3
