---
version: 1
service:
  name: '{{ env "bamboo_deploy_environment" }}-{{ env "bamboo_shortPlanName" }}'
  shortname: ""
  owner: lab
deployment:
  strategy: blueGreen
health:
  delayseconds: 0
  path: "/"
  port: 8989
args:
  - "-pg"
  - "/data/graphdata/germany-latest.osm-gh"
  - "-dp"
  - "s3://lab-graphhopper-graphdata-prod/germany-latest.gz"
ports:
  - 8989
limits:
  cpu: 2
  memory: 8192
ingress:
  hosts:
    - host: 'api-graphhopper-{{ env "bamboo_deploy_environment" }}.{{ env "bamboo_deploy_host" }}'
      public: false
